// https://souffle-lang.github.io/constraints

.decl stringTable(t:symbol)
.decl substringTable(t:symbol)
.decl outputData(substrs:symbol, str:symbol)
.output outputData
outputData(x,y) :- substringTable(x), stringTable(y), contains(x,y).
stringTable("aaaa").
stringTable("abba").
stringTable("bcab").
stringTable("bdab").
substringTable("a").
substringTable("ab").
substringTable("cab").

.decl inputData(t:symbol)
.decl outputData2(t:symbol)
.output outputData2
outputData2(x) :- inputData(x), match("a.*",x).
inputData("aaaa").
inputData("abba").
inputData("bcab").
inputData("bdab").
